import { AdminActionSpec, AdminPageSpec, FieldControl } from "./types";

const field = (key: string, label: string, control: FieldControl = "input", required = false) => ({
  key,
  label,
  control,
  required,
});

const optionField = (key: string, label: string, options: string[], control: FieldControl = "select") => ({
  key,
  label,
  control,
  options,
});

const column = (key: string, label: string, extra: { sensitive?: boolean; moneyCent?: boolean; width?: number } = {}) => ({
  key,
  label,
  ...extra,
});

const action = (
  key: string,
  label: string,
  permission: string,
  extra: Partial<AdminActionSpec> = {},
): AdminActionSpec => ({
  key,
  label,
  permission,
  ...extra,
});

const highRiskAction = (key: string, label: string, permission: string, api?: string): AdminActionSpec =>
  action(key, label, permission, {
    api,
    method: "POST",
    highRisk: true,
    confirmRequired: true,
    reasonRequired: true,
  });

export const adminPages: AdminPageSpec[] = [
  {
    path: "/admin/dashboard",
    title: "数据总览",
    navGroup: "运营",
    permission: "admin.dashboard.read",
    apiKey: "dashboard.list",
    searchFields: [field("bizDate", "业务日期", "date_range")],
    tableColumns: [
      column("todayScanUsers", "今日扫码人数"),
      column("todayAdViews", "今日广告展示"),
      column("todayAdCompletes", "今日广告完成"),
      column("todayConnectSuccess", "今日连接成功"),
      column("todayEstimatedRevenueCent", "今日预估总收益", { moneyCent: true }),
      column("todayMerchantShareCent", "今日商户分成", { moneyCent: true }),
      column("todayPlatformRevenueCent", "今日平台收益", { moneyCent: true }),
      column("pendingWithdrawCount", "待审核提现"),
      column("abnormalRiskEventCount", "异常风控事件"),
      column("activeStoreCount", "活跃门店数"),
    ],
    formFields: [],
    actions: [action("refresh", "刷新", "admin.dashboard.read"), action("export", "导出日报", "admin.dashboard.read")],
    emptyState: "暂无运营数据",
    loadingText: "正在加载运营数据",
    errorText: "数据总览加载失败",
    forbiddenText: "无权查看数据总览",
    complianceNotice: "今日收益为预估金额，最终以平台实际结算和风控审核为准。",
  },
  {
    path: "/admin/merchant-applications",
    title: "商户申请审核",
    navGroup: "商户",
    permission: "merchant.audit",
    apiKey: "merchantApplications.list",
    searchFields: [
      field("applicationNo", "申请编号"),
      field("merchantName", "商户名称"),
      field("ownerPhone", "负责人手机号"),
      optionField("city", "城市", ["上海", "北京", "广州", "深圳"]),
      optionField("status", "状态", ["pending", "approved", "rejected", "duplicated"]),
      field("createdAtRange", "提交时间", "date_range"),
    ],
    tableColumns: [
      column("applicationNo", "申请编号"),
      column("merchantName", "商户名称"),
      column("storeName", "门店名称"),
      column("ownerName", "负责人"),
      column("ownerPhone", "手机号", { sensitive: true }),
      column("city", "城市"),
      column("industry", "行业"),
      column("status", "状态"),
      column("createdAt", "提交时间"),
    ],
    formFields: [
      field("reviewRemark", "审核备注", "textarea", true),
      field("createMerchant", "创建商户", "switch"),
      field("createStore", "创建门店", "switch"),
      field("bindOwner", "绑定老板", "switch"),
      field("createWifiIfProvided", "配置申请 WiFi", "switch"),
    ],
    actions: [
      action("detail", "查看详情", "merchant.audit", { api: "merchantApplications.list", method: "GET" }),
      highRiskAction("approve", "审核通过", "merchant.audit", "merchantApplications.approve"),
      highRiskAction("reject", "驳回", "merchant.audit", "merchantApplications.reject"),
      action("markDuplicate", "标记重复", "merchant.audit"),
      action("logs", "查看日志", "operation_log.read"),
    ],
    emptyState: "暂无商户申请",
    loadingText: "正在加载申请列表",
    errorText: "商户申请加载失败",
    forbiddenText: "无权审核商户申请",
  },
  {
    path: "/admin/merchants",
    title: "商户管理",
    navGroup: "商户",
    permission: "admin.dashboard.read",
    apiKey: "merchants.list",
    searchFields: [
      field("keyword", "商户名称/编号/手机号"),
      optionField("status", "状态", ["pending", "active", "disabled", "risk_frozen"]),
      optionField("riskStatus", "风控状态", ["normal", "watch", "frozen", "blocked"]),
      field("city", "城市"),
      field("industry", "行业"),
      field("createdAtRange", "创建时间", "date_range"),
    ],
    tableColumns: [
      column("merchantNo", "商户编号"),
      column("name", "商户名称"),
      column("ownerName", "老板姓名"),
      column("ownerPhone", "手机号", { sensitive: true }),
      column("city", "城市"),
      column("industry", "行业"),
      column("storeCount", "门店数"),
      column("shareRateBps", "商户分成比例"),
      column("availableCent", "钱包可提现", { moneyCent: true }),
      column("status", "状态"),
      column("riskStatus", "风控状态"),
    ],
    formFields: [
      field("name", "商户名称", "input", true),
      field("ownerName", "老板姓名"),
      field("ownerPhone", "手机号"),
      field("city", "城市"),
      field("industry", "行业"),
      field("remark", "备注", "textarea"),
      field("shareRateBps", "新比例", "number"),
      field("reason", "修改原因", "textarea", true),
      field("confirm", "二次确认", "switch", true),
    ],
    actions: [
      action("create", "新增", "merchant.create", { api: "merchants.create", method: "POST" }),
      action("edit", "编辑", "merchant.create"),
      highRiskAction("disable", "禁用", "merchant.disable"),
      action("enable", "启用", "merchant.create"),
      action("bindOwner", "绑定老板", "merchant.audit"),
      highRiskAction("shareRate", "修改分成比例", "merchant.share_rate.write", "merchants.shareRate"),
      action("stores", "查看门店", "admin.dashboard.read"),
      action("wallet", "查看钱包", "wallet.read"),
    ],
    emptyState: "暂无商户",
    loadingText: "正在加载商户",
    errorText: "商户列表加载失败",
    forbiddenText: "无权查看商户",
  },
  {
    path: "/admin/stores",
    title: "门店管理",
    navGroup: "商户",
    permission: "admin.dashboard.read",
    apiKey: "stores.list",
    searchFields: [
      field("keyword", "门店名称/编号"),
      field("merchant", "商户"),
      field("city", "城市"),
      field("industry", "行业"),
      optionField("status", "状态", ["active", "disabled", "risk_frozen"]),
      optionField("wifiStatus", "是否配置 WiFi", ["已配置", "未配置"]),
    ],
    tableColumns: [
      column("storeNo", "门店编号"),
      column("name", "门店名称"),
      column("merchantName", "所属商户"),
      column("city", "城市"),
      column("address", "地址"),
      column("industry", "行业"),
      column("shareRateBps", "门店分成比例"),
      column("wifiStatus", "WiFi 状态"),
      column("qrcodeStatus", "二维码状态"),
      column("status", "状态"),
    ],
    formFields: [
      field("merchantId", "所属商户", "select", true),
      field("name", "门店名称", "input", true),
      field("city", "城市"),
      field("district", "区县"),
      field("address", "地址"),
      field("industry", "行业"),
      field("contactName", "联系人"),
      field("contactPhone", "联系电话"),
      field("shareRateBps", "门店特殊分成比例", "number"),
      optionField("status", "状态", ["active", "disabled"]),
    ],
    actions: [
      action("create", "新增", "store.create", { api: "stores.create", method: "POST" }),
      action("edit", "编辑", "store.create"),
      highRiskAction("disable", "禁用", "store.create"),
      highRiskAction("enable", "启用", "store.create"),
      action("wifi", "配置 WiFi", "wifi.write"),
      action("qrcode", "生成二维码", "store.create", { api: "qrcodes.generate", method: "POST" }),
      highRiskAction("shareRate", "修改分成比例", "store.share_rate.write"),
    ],
    emptyState: "暂无门店",
    loadingText: "正在加载门店",
    errorText: "门店列表加载失败",
    forbiddenText: "无权查看门店",
  },
  {
    path: "/admin/wifi",
    title: "WiFi 管理",
    navGroup: "商户",
    permission: "admin.dashboard.read",
    apiKey: "wifi.list",
    searchFields: [
      field("store", "门店"),
      field("merchant", "商户"),
      field("ssid", "SSID"),
      optionField("status", "状态", ["enabled", "disabled", "unconfigured"]),
      optionField("connectMode", "连接模式", ["mock", "wechat", "manual"]),
      field("city", "城市"),
    ],
    tableColumns: [
      column("storeName", "门店"),
      column("merchantName", "商户"),
      column("ssid", "SSID"),
      column("passwordMasked", "密码脱敏", { sensitive: true }),
      column("securityType", "加密类型"),
      column("connectMode", "连接模式"),
      column("allowCopyPassword", "允许复制"),
      column("showManualFallback", "手动兜底"),
      column("wifiStatus", "启用状态"),
      column("updatedAt", "更新时间"),
    ],
    formFields: [
      field("storeId", "门店", "select", true),
      field("ssid", "SSID", "input", true),
      field("password", "密码", "password"),
      optionField("securityType", "加密类型", ["none", "WEP", "WPA", "WPA2", "WPA3"]),
      optionField("connectMode", "连接模式", ["mock", "wechat", "manual"]),
      field("isPrimary", "主 WiFi", "switch"),
      field("isEnabled", "启用", "switch"),
      field("allowCopyPassword", "允许复制", "switch"),
      field("showManualFallback", "手动兜底", "switch"),
      optionField("passwordViewPolicy", "密码查看策略", ["never_plain", "copy_only", "second_confirm_plain"]),
      field("remark", "备注", "textarea"),
    ],
    actions: [
      action("create", "新增", "wifi.write", { api: "wifi.save", method: "POST" }),
      action("edit", "编辑", "wifi.write", { api: "wifi.save", method: "POST" }),
      highRiskAction("disable", "禁用", "wifi.write"),
      highRiskAction("enable", "启用", "wifi.write"),
      highRiskAction("resetPassword", "重置密码", "wifi.write", "wifi.save"),
      highRiskAction("copyPassword", "复制密码", "wifi.password.copy"),
      action("failures", "查看连接失败", "risk.read"),
    ],
    emptyState: "未配置",
    loadingText: "正在加载 WiFi 配置",
    errorText: "WiFi 配置加载失败",
    forbiddenText: "无权查看 WiFi 配置",
  },
  {
    path: "/admin/qrcodes",
    title: "二维码管理",
    navGroup: "商户",
    permission: "admin.dashboard.read",
    apiKey: "qrcodes.list",
    searchFields: [field("store", "门店"), field("merchant", "商户"), optionField("status", "二维码状态", ["active", "disabled"])],
    tableColumns: [
      column("storeName", "门店"),
      column("merchantName", "商户"),
      column("scene", "scene"),
      column("qrcodeUrl", "二维码预览"),
      column("status", "状态"),
      column("createdAt", "创建时间"),
    ],
    formFields: [field("storeId", "门店", "select", true)],
    actions: [
      action("generate", "生成", "store.create", { api: "qrcodes.generate", method: "POST" }),
      action("download", "下载", "admin.dashboard.read"),
      highRiskAction("disable", "禁用", "store.create"),
      highRiskAction("regenerate", "重新生成", "store.create"),
    ],
    emptyState: "暂无二维码",
    loadingText: "正在加载二维码",
    errorText: "二维码加载失败",
    forbiddenText: "无权查看二维码",
  },
  {
    path: "/admin/ads",
    title: "广告管理",
    navGroup: "广告",
    permission: "ads.read",
    apiKey: "ads.list",
    searchFields: [field("name", "广告名称"), optionField("type", "类型", ["mock", "wechat", "self", "cpa", "cps"]), optionField("status", "状态", ["draft", "active", "disabled"])],
    tableColumns: [
      column("adNo", "广告编号"),
      column("name", "名称"),
      column("type", "类型"),
      column("materialUrl", "素材预览"),
      column("landingUrl", "落地页"),
      column("status", "状态"),
      column("auditReason", "审核原因"),
      column("createdAt", "创建时间"),
    ],
    formFields: [field("name", "广告名称", "input", true), optionField("type", "广告类型", ["mock", "wechat", "self", "cpa", "cps"]), field("materialUrl", "素材 URL", "input"), field("landingUrl", "落地页", "input"), field("remark", "备注", "textarea")],
    actions: [
      action("create", "新增", "ads.write", { api: "ads.save", method: "POST" }),
      action("edit", "编辑", "ads.write"),
      action("submit", "提交审核", "ads.write"),
      highRiskAction("approve", "审核通过", "ads.write"),
      highRiskAction("reject", "驳回", "ads.write"),
      highRiskAction("disable", "禁用", "ads.write"),
      action("preview", "预览", "ads.read"),
    ],
    emptyState: "暂无广告",
    loadingText: "正在加载广告",
    errorText: "广告加载失败",
    forbiddenText: "无权查看广告",
  },
  {
    path: "/admin/campaigns",
    title: "广告投放",
    navGroup: "广告",
    permission: "ads.read",
    apiKey: "campaigns.list",
    searchFields: [field("name", "投放名称"), field("city", "城市"), field("industry", "行业"), field("store", "门店"), optionField("status", "状态", ["active", "paused", "ended"])],
    tableColumns: [
      column("campaignNo", "投放编号"),
      column("adName", "广告"),
      column("name", "投放名称"),
      column("priority", "优先级"),
      column("targetCities", "定向城市"),
      column("targetIndustries", "定向行业"),
      column("targetStoreCount", "定向门店数"),
      column("shareRateBps", "活动分成比例"),
      column("startedAt", "开始时间"),
      column("endedAt", "结束时间"),
      column("status", "状态"),
    ],
    formFields: [field("adId", "广告", "select", true), field("name", "投放名称", "input", true), field("priority", "优先级", "number"), field("targetCities", "定向城市", "multi_select"), field("targetIndustries", "定向行业", "multi_select"), field("shareRateBps", "活动分成比例", "number")],
    actions: [
      action("create", "新增", "ads.write", { api: "campaigns.save", method: "POST" }),
      action("edit", "编辑", "ads.write"),
      highRiskAction("pause", "暂停", "ads.write"),
      action("enable", "启用", "ads.write"),
      highRiskAction("end", "结束", "ads.write"),
      action("selectStores", "选择门店", "ads.write"),
    ],
    emptyState: "暂无广告投放",
    loadingText: "正在加载投放",
    errorText: "广告投放加载失败",
    forbiddenText: "无权查看广告投放",
  },
  {
    path: "/admin/revenue",
    title: "收益管理",
    navGroup: "财务",
    permission: "revenue.read",
    apiKey: "revenue.list",
    searchFields: [field("merchant", "商户"), field("store", "门店"), optionField("status", "状态", ["estimated", "withdrawable", "invalid"]), field("date", "日期", "date_range"), field("adType", "广告类型")],
    tableColumns: [
      column("revenueNo", "收益编号"),
      column("merchantName", "商户"),
      column("storeName", "门店"),
      column("viewNo", "广告观看记录"),
      column("grossAmountCent", "毛收入", { moneyCent: true }),
      column("merchantAmountCent", "商户收益", { moneyCent: true }),
      column("platformAmountCent", "平台收益", { moneyCent: true }),
      column("appliedShareRateBps", "应用比例"),
      column("shareRuleSource", "规则来源"),
      column("status", "状态"),
    ],
    formFields: [field("revenueNos", "收益编号", "multi_select"), field("remark", "结算备注", "textarea")],
    actions: [
      action("detail", "查看", "revenue.read"),
      highRiskAction("confirm", "确认结算", "revenue.confirm", "settlement.import"),
      highRiskAction("invalidate", "作废", "revenue.confirm"),
      highRiskAction("recalculate", "人工重算", "revenue.confirm"),
      action("export", "导出", "revenue.read"),
    ],
    emptyState: "暂无收益记录",
    loadingText: "正在加载收益",
    errorText: "收益记录加载失败",
    forbiddenText: "无权查看收益",
    complianceNotice: "预估收益不等于可提现收益，以结算确认和风控审核后金额为准。",
  },
  {
    path: "/admin/wallets",
    title: "钱包管理",
    navGroup: "财务",
    permission: "wallet.read",
    apiKey: "wallets.list",
    searchFields: [field("merchant", "商户"), field("amountRange", "余额范围", "money"), optionField("freezeStatus", "冻结状态", ["normal", "withdraw_frozen", "risk_frozen"])],
    tableColumns: [
      column("merchantName", "商户"),
      column("totalConfirmedCent", "累计确认", { moneyCent: true }),
      column("availableCent", "可提现", { moneyCent: true }),
      column("frozenWithdrawCent", "提现冻结", { moneyCent: true }),
      column("frozenRiskCent", "风控冻结", { moneyCent: true }),
      column("totalWithdrawnCent", "累计提现", { moneyCent: true }),
      column("updatedAt", "更新时间"),
    ],
    formFields: [field("merchantId", "商户", "select", true), optionField("type", "类型", ["add", "sub"]), field("amountCent", "金额", "money", true), field("reason", "原因", "textarea", true), field("attachment", "附件", "upload"), field("confirm", "二次确认", "switch", true)],
    actions: [
      action("ledger", "查看流水", "wallet.read"),
      highRiskAction("adjust", "人工调账", "wallet.adjust", "wallets.adjust"),
      highRiskAction("riskFreeze", "风控冻结", "risk.handle"),
      highRiskAction("riskUnfreeze", "风控解冻", "risk.handle"),
    ],
    emptyState: "暂无钱包数据",
    loadingText: "正在加载钱包",
    errorText: "钱包数据加载失败",
    forbiddenText: "无权查看钱包",
  },
  {
    path: "/admin/withdraws",
    title: "提现管理",
    navGroup: "财务",
    permission: "withdraw.read",
    apiKey: "withdraws.list",
    searchFields: [field("withdrawNo", "提现单号"), field("merchant", "商户"), field("openid", "openid"), optionField("status", "状态", ["frozen", "reviewing", "transfer_processing", "paid", "failed", "rejected"]), field("amount", "金额", "money"), field("appliedAt", "申请时间", "date_range")],
    tableColumns: [
      column("withdrawNo", "提现单号"),
      column("merchantName", "商户"),
      column("openidMasked", "openid脱敏", { sensitive: true }),
      column("amountCent", "金额", { moneyCent: true }),
      column("status", "状态"),
      column("outBillNo", "out_bill_no"),
      column("failReason", "失败原因"),
      column("appliedAt", "申请时间"),
      column("paidAt", "打款时间"),
    ],
    formFields: [field("reason", "审核原因", "textarea", true), field("confirm", "二次确认", "switch", true)],
    actions: [
      action("detail", "查看", "withdraw.read"),
      highRiskAction("approve", "审核通过", "withdraw.review", "withdraws.approve"),
      highRiskAction("reject", "审核拒绝", "withdraw.review"),
      action("query", "查单", "withdraw.review"),
      highRiskAction("abnormal", "标记异常", "withdraw.review"),
      action("export", "导出", "withdraw.read"),
    ],
    emptyState: "暂无提现记录",
    loadingText: "正在加载提现",
    errorText: "提现记录加载失败",
    forbiddenText: "无权查看提现",
    complianceNotice: "审核通过只发起转账，必须等待 Mock/微信最终确认后才能标记到账。",
  },
  {
    path: "/admin/reconciliation",
    title: "财务对账",
    navGroup: "财务",
    permission: "reconciliation.read",
    apiKey: "reconciliation.list",
    searchFields: [optionField("type", "对账类型", ["withdraw", "wallet_ledger", "revenue_settlement"]), field("bizDate", "业务日期", "date_range"), optionField("status", "状态", ["matched", "different", "pending"])],
    tableColumns: [
      column("reconcileNo", "对账编号"),
      column("type", "对账类型"),
      column("bizDate", "业务日期"),
      column("localAmountCent", "本地金额", { moneyCent: true }),
      column("remoteAmountCent", "外部金额", { moneyCent: true }),
      column("diffAmountCent", "差异金额", { moneyCent: true }),
      column("status", "状态"),
      column("handledBy", "处理人"),
      column("handledAt", "处理时间"),
    ],
    formFields: [field("bizDate", "业务日期", "date_range", true), optionField("type", "对账类型", ["withdraw", "wallet_ledger", "revenue_settlement"]), field("remark", "备注", "textarea")],
    actions: [
      action("run", "发起对账", "reconciliation.handle", { api: "reconciliation.run", method: "POST" }),
      action("detail", "查看详情", "reconciliation.read"),
      highRiskAction("markMatched", "标记一致", "reconciliation.handle"),
      highRiskAction("markDifferent", "标记差异", "reconciliation.handle"),
      highRiskAction("manualHandle", "人工处理", "reconciliation.handle"),
      action("export", "导出报表", "reconciliation.read"),
    ],
    emptyState: "暂无对账记录",
    loadingText: "正在加载对账",
    errorText: "对账记录加载失败",
    forbiddenText: "无权查看财务对账",
  },
  {
    path: "/admin/ranking",
    title: "排行榜配置",
    navGroup: "运营",
    permission: "ranking.read",
    apiKey: "ranking.config",
    searchFields: [optionField("enabled", "是否开启", ["true", "false"])],
    tableColumns: [
      column("enabled", "是否开启"),
      column("enabledTypes", "榜单类型"),
      column("limit", "展示数量"),
      column("amountDisplayMode", "金额展示模式"),
      column("refreshMinutes", "刷新频率"),
      column("hideRiskStores", "隐藏风控门店"),
      column("minRevenueCent", "参与门槛", { moneyCent: true }),
      column("visibleScope", "可见范围"),
    ],
    formFields: [field("enabled", "是否开启", "switch"), optionField("enabledTypes", "榜单类型", ["today_revenue", "yesterday_revenue", "month_revenue", "total_revenue", "scan_count", "ad_complete_count", "connect_success_count"], "multi_select"), field("limit", "展示数量", "number"), optionField("amountDisplayMode", "金额展示模式", ["exact", "range", "heat", "hidden"]), field("refreshMinutes", "刷新频率", "number"), field("hideRiskStores", "隐藏风控门店", "switch"), field("hideNewStores", "隐藏新店", "switch"), field("newStoreDays", "新店天数", "number"), field("minRevenueCent", "参与门槛", "money"), optionField("visibleScope", "商户可见范围", ["global", "city", "industry"])],
    actions: [
      highRiskAction("save", "保存", "ranking.write", "ranking.save"),
      action("refresh", "立即刷新", "ranking.write"),
      action("preview", "预览", "ranking.read"),
    ],
    emptyState: "暂无排行榜配置变更",
    loadingText: "正在加载排行榜配置",
    errorText: "排行榜配置加载失败",
    forbiddenText: "无权查看排行榜配置",
  },
  {
    path: "/admin/risk-events",
    title: "风控中心",
    navGroup: "风控",
    permission: "risk.read",
    apiKey: "riskEvents.list",
    searchFields: [field("riskType", "风险类型"), optionField("level", "等级", ["low", "medium", "high", "critical"]), optionField("status", "状态", ["open", "handled", "ignored"]), field("merchant", "商户"), field("store", "门店"), field("openid", "openid"), field("createdAt", "时间", "date_range")],
    tableColumns: [
      column("eventNo", "事件编号"),
      column("riskType", "类型"),
      column("level", "等级"),
      column("merchantName", "商户"),
      column("storeName", "门店"),
      column("openidMasked", "openid脱敏", { sensitive: true }),
      column("description", "描述"),
      column("status", "状态"),
      column("createdAt", "创建时间"),
      column("handledBy", "处理人"),
    ],
    formFields: [optionField("action", "处理动作", ["ignore", "freeze_revenue", "pause_withdraw", "disable_store", "disable_merchant", "recover", "remark"]), field("remark", "处理备注", "textarea", true), field("confirm", "二次确认", "switch", true)],
    actions: [
      action("ignore", "忽略", "risk.handle", { api: "riskEvents.handle", method: "POST" }),
      highRiskAction("freezeRevenue", "冻结收益", "risk.handle", "riskEvents.handle"),
      highRiskAction("pauseWithdraw", "暂停提现", "risk.handle", "riskEvents.handle"),
      highRiskAction("disableStore", "禁用门店", "risk.handle", "riskEvents.handle"),
      highRiskAction("disableMerchant", "禁用商户", "risk.handle", "riskEvents.handle"),
      highRiskAction("recover", "恢复", "risk.handle", "riskEvents.handle"),
      action("remark", "备注", "risk.handle", { api: "riskEvents.handle", method: "POST" }),
    ],
    emptyState: "暂无风控事件",
    loadingText: "正在加载风控事件",
    errorText: "风控事件加载失败",
    forbiddenText: "无权查看风控中心",
  },
  {
    path: "/admin/system-config",
    title: "系统配置",
    navGroup: "系统",
    permission: "system_config.read",
    apiKey: "systemConfig.list",
    searchFields: [field("key", "配置 key"), optionField("module", "分组", ["system", "compliance", "wifi", "ad", "commission", "withdraw", "ranking", "risk"])],
    tableColumns: [
      column("name", "配置名"),
      column("key", "key"),
      column("value", "当前值", { sensitive: true }),
      column("default", "默认值"),
      column("sensitive", "是否敏感"),
      column("requiredForProduction", "生产必填"),
      column("restartRequired", "是否需要重启"),
    ],
    formFields: [field("key", "配置 key", "readonly"), field("value", "当前值", "input"), field("reason", "修改原因", "textarea", true), field("confirm", "二次确认", "switch", true)],
    actions: [
      action("edit", "编辑", "system_config.read"),
      highRiskAction("save", "保存", "system_config.write", "systemConfig.save"),
      highRiskAction("restore", "恢复默认", "system_config.write"),
      action("logs", "查看修改日志", "operation_log.read"),
    ],
    emptyState: "暂无系统配置",
    loadingText: "正在加载系统配置",
    errorText: "系统配置加载失败",
    forbiddenText: "无权查看系统配置",
  },
  {
    path: "/admin/integrations",
    title: "第三方配置状态",
    navGroup: "系统",
    permission: "system_config.read",
    apiKey: "integrations.status",
    searchFields: [optionField("status", "状态", ["未配置", "已配置", "验证通过", "验证失败"])],
    tableColumns: [
      column("wechatAppId", "微信 AppID", { sensitive: true }),
      column("wechatAppSecret", "AppSecret", { sensitive: true }),
      column("rewardAdUnitId", "广告位", { sensitive: true }),
      column("wechatPayMchId", "支付商户号", { sensitive: true }),
      column("apiV3Key", "API v3", { sensitive: true }),
      column("certPath", "证书路径", { sensitive: true }),
      column("callbackDomain", "回调域名"),
      column("transferPermission", "商家转账权限"),
      column("storage", "对象存储"),
    ],
    formFields: [],
    actions: [action("check", "检测配置", "system_config.read"), action("error", "查看错误", "system_config.read"), action("copyMissing", "复制缺失项", "system_config.read")],
    emptyState: "暂无第三方配置状态",
    loadingText: "正在检测第三方状态",
    errorText: "第三方状态检测失败",
    forbiddenText: "无权查看第三方配置状态",
    complianceNotice: "敏感值不在后台明文显示，只显示是否存在；开发阶段全部使用 Mock/Adapter。",
  },
  {
    path: "/admin/permissions",
    title: "权限管理",
    navGroup: "系统",
    permission: "permission.read",
    apiKey: "adminUsers.list",
    searchFields: [field("username", "后台账号"), optionField("role", "角色", ["super_admin", "operator", "finance", "risk", "customer_service", "readonly_audit"])],
    tableColumns: [column("username", "后台账号"), column("role", "角色"), column("status", "状态"), column("lastLoginAt", "最后登录"), column("permissionMatrix", "权限矩阵")],
    formFields: [field("username", "账号", "input", true), optionField("role", "角色", ["super_admin", "operator", "finance", "risk", "customer_service", "readonly_audit"]), field("status", "启用", "switch")],
    actions: [
      action("create", "新增账号", "permission.write", { api: "adminUsers.create", method: "POST" }),
      action("roles", "角色矩阵", "permission.read"),
      highRiskAction("disable", "禁用账号", "permission.write"),
    ],
    emptyState: "暂无后台账号",
    loadingText: "正在加载权限",
    errorText: "权限数据加载失败",
    forbiddenText: "无权查看权限管理",
  },
  {
    path: "/admin/operation-logs",
    title: "操作日志",
    navGroup: "系统",
    permission: "operation_log.read",
    apiKey: "operationLogs.list",
    searchFields: [field("actor", "操作者"), field("action", "动作"), field("target", "目标"), field("ip", "IP"), field("createdAt", "时间", "date_range")],
    tableColumns: [
      column("actorId", "操作者"),
      column("action", "动作"),
      column("targetType", "目标类型"),
      column("targetId", "目标 ID"),
      column("diffSummary", "前后差异摘要"),
      column("ip", "IP"),
      column("createdAt", "时间"),
    ],
    formFields: [],
    actions: [action("detail", "查看详情", "operation_log.read"), action("export", "导出", "operation_log.read")],
    emptyState: "暂无操作日志",
    loadingText: "正在加载操作日志",
    errorText: "操作日志加载失败",
    forbiddenText: "无权查看操作日志",
  },
];

export const getAdminPage = (path: string) => adminPages.find((page) => page.path === path);
