import { ApiEndpointSpec } from "./types";

export const adminApiEndpoints: ApiEndpointSpec[] = [
  { key: "dashboard.list", method: "GET", path: "/api/admin/dashboard", permission: "admin.dashboard.read", mockSafe: true },
  { key: "merchantApplications.list", method: "GET", path: "/api/admin/merchant-applications", permission: "merchant.audit", mockSafe: true },
  { key: "merchantApplications.approve", method: "POST", path: "/api/admin/merchant-applications/:applicationNo/approve", permission: "merchant.audit", mockSafe: true },
  { key: "merchantApplications.reject", method: "POST", path: "/api/admin/merchant-applications/:applicationNo/reject", permission: "merchant.audit", mockSafe: true },
  { key: "merchants.list", method: "GET", path: "/api/admin/merchants", permission: "admin.dashboard.read", mockSafe: true },
  { key: "merchants.create", method: "POST", path: "/api/admin/merchants", permission: "merchant.create", mockSafe: true },
  { key: "merchants.shareRate", method: "POST", path: "/api/admin/merchants/:id/share-rate", permission: "merchant.share_rate.write", mockSafe: true },
  { key: "stores.list", method: "GET", path: "/api/admin/stores", permission: "admin.dashboard.read", mockSafe: true },
  { key: "stores.create", method: "POST", path: "/api/admin/stores", permission: "store.create", mockSafe: true },
  { key: "wifi.list", method: "GET", path: "/api/admin/wifi", permission: "admin.dashboard.read", mockSafe: true },
  { key: "wifi.save", method: "POST", path: "/api/admin/wifi/save", permission: "wifi.write", mockSafe: true },
  { key: "qrcodes.list", method: "GET", path: "/api/admin/qrcodes", permission: "admin.dashboard.read", mockSafe: true },
  { key: "qrcodes.generate", method: "POST", path: "/api/admin/qrcode/generate", permission: "store.create", mockSafe: true },
  { key: "ads.list", method: "GET", path: "/api/admin/ads", permission: "ads.read", mockSafe: true },
  { key: "ads.save", method: "POST", path: "/api/admin/ads", permission: "ads.write", mockSafe: true },
  { key: "campaigns.list", method: "GET", path: "/api/admin/campaigns", permission: "ads.read", mockSafe: true },
  { key: "campaigns.save", method: "POST", path: "/api/admin/campaigns", permission: "ads.write", mockSafe: true },
  { key: "revenue.list", method: "GET", path: "/api/admin/revenue", permission: "revenue.read", mockSafe: true },
  { key: "settlement.import", method: "POST", path: "/api/admin/settlement/import", permission: "revenue.confirm", mockSafe: true },
  { key: "wallets.list", method: "GET", path: "/api/admin/wallets", permission: "wallet.read", mockSafe: true },
  { key: "wallets.adjust", method: "POST", path: "/api/admin/wallets/adjust", permission: "wallet.adjust", mockSafe: true },
  { key: "withdraws.list", method: "GET", path: "/api/admin/withdraws", permission: "withdraw.read", mockSafe: true },
  { key: "withdraws.approve", method: "POST", path: "/api/admin/withdraws/:id/approve", permission: "withdraw.review", mockSafe: true },
  { key: "reconciliation.list", method: "GET", path: "/api/admin/reconciliation", permission: "reconciliation.read", mockSafe: true },
  { key: "reconciliation.run", method: "POST", path: "/api/admin/reconciliation/run", permission: "reconciliation.handle", mockSafe: true },
  { key: "ranking.config", method: "GET", path: "/api/admin/ranking/config", permission: "ranking.read", mockSafe: true },
  { key: "ranking.save", method: "POST", path: "/api/admin/ranking/config", permission: "ranking.write", mockSafe: true },
  { key: "riskEvents.list", method: "GET", path: "/api/admin/risk/events", permission: "risk.read", mockSafe: true },
  { key: "riskEvents.handle", method: "POST", path: "/api/admin/risk/events/:id/handle", permission: "risk.handle", mockSafe: true },
  { key: "systemConfig.list", method: "GET", path: "/api/admin/system/config", permission: "system_config.read", mockSafe: true },
  { key: "systemConfig.save", method: "POST", path: "/api/admin/system/config", permission: "system_config.write", mockSafe: true },
  { key: "integrations.status", method: "GET", path: "/api/admin/integrations/status", permission: "system_config.read", mockSafe: true },
  { key: "operationLogs.list", method: "GET", path: "/api/admin/operation-logs", permission: "operation_log.read", mockSafe: true },
  { key: "adminUsers.list", method: "GET", path: "/api/admin/admin-users", permission: "permission.read", mockSafe: true },
  { key: "adminUsers.create", method: "POST", path: "/api/admin/admin-users", permission: "permission.write", mockSafe: true },
  { key: "roles.list", method: "GET", path: "/api/admin/roles", permission: "permission.read", mockSafe: true },
];

export const findAdminEndpoint = (key: string) => adminApiEndpoints.find((endpoint) => endpoint.key === key);
