version: '3.9'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wifi_ad
    ports: ['3306:3306']
  redis:
    image: redis:7
    ports: ['6379:6379']
